### ISSUE TITLE
About the T-Rex data process script

### ISSUE THREAD

**Issue by Frankie123421** [fc-liu/EI_ORE#1]
Hey, congratulations on your nice work. I have tried to use T-Rex data process script but failed. Could you please tell me how to use it? Thank you.

**Comment by gxxxzhang** [comment]
> 嘿，恭喜你做得很好。我尝试使用T-Rex数据处理脚本，但失败了。你能告诉我如何使用它吗？谢谢。

Hello, have you solved the problem of T-Rex data preprocessing？
