### ISSUE TITLE
Where did you get the JSON files in the code?

### ISSUE THREAD

**Issue by seanswyi** [fc-liu/EI_ORE#3]
Hi. Did you use separate preprocessing scripts for the JSON files in your code? For example, the `json-ds-val.json`, `entity.json` files. It doesn't seem that difficult to get these values from the TSV output of the C++ script, but I just wanted to ask if you plan on releasing the data in the near future or not.

Thanks!

**Comment by fc-liu** [comment]
Hi， you can obtain the json format files through [convert_json_main](https://github.com/fc-liu/EI_ORE/blob/1602fd69fc9fd6794716caf362330452b70a1b35/data_processing/data_process.py#L202) method in data_process file. The entity.json depends on an ES api, we will later release a sampled file.

**Comment by seanswyi** [comment]
Okay, thanks. I just wanted to clarify, would the code still run without the entity file?

**Comment by fc-liu** [comment]
no, the entity file is requisite for element intervention.

**Comment by seanswyi** [comment]
Got it, just wanted to make sure. Thanks again.

**Comment by fc-liu** [comment]
you're welcome😊
